pipeline {
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        
        stage('Checkout') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'github_access_credentials', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PASSWORD')]) {
                    script {
                        git credentialsId: 'github_access_credentials', 
                        url: 'https://github.com/A-asava/Webstack-Portfolio-Project_CI-CD-Pipeline/tree/main/python-jenkins-argocd-k8s',
                        branch: 'main'
                    }
                }
            }
        }

        stage('Build Docker') {
            steps {
                script {
                    sh '''
                    echo 'Build Docker Image'
                    docker build -t mudeizi/cicd-e2e:${IMAGE_TAG} .
                    '''
                }
            }
        }

        stage('Push the artifacts') {
            steps {
                // Using Docker Hub credentials here
                withCredentials([usernamePassword(credentialsId: 'dockerhub_access_credentials', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                    script {
                        sh '''
                        echo 'Login to Docker Hub'
                        echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
                        echo 'Push to Docker Hub'
                        docker push mudeizi/cicd-e2e:${IMAGE_TAG}
                        '''
                    }
                }
            }
        }

        stage('Checkout K8S manifest SCM') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'github_access_credentials', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PASSWORD')]) {
                    script {
                        git credentialsId: 'github_access_credentials',
                        url: 'https://github.com/A-asava/portfolio_project_manifest_repo.git',
                        branch: 'main'
                    }
                }
            }
        }

        stage('Update K8S manifest & push to Repo') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'github_access_credentials', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PASSWORD')]) {
                        sh '''
                        echo 'Updating K8S manifest'
                        sed -i "s/32/${IMAGE_TAG}/g" deploy.yaml
                        git add deploy.yaml
                        git commit -m 'Updated the deploy yaml | Jenkins Pipeline'
                        echo ${GIT_PASSWORD} | git push https://github.com/A-asava/portfolio_project_manifest_repo HEAD:main
                        '''
                    }
                }
            }
        }
    }
}

